config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :surveys
  get 'sessions/login'
  post 'sessions/login'
  get 'sessions/logout'

  resources :authors

  root 'surveys#index'

  resources 'forms', :only => [:new, :create]
  

end

app/models/answer_choice.rb
class AnswerChoice < ActiveRecord::Base
  belongs_to :question
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_secure_password

  has_many :surveys, dependent: :destroy

  validates :email, presence: true
  validates :password, presence: true

end

app/models/form.rb
class Form < ActiveRecord::Base
  has_many :responses, dependent: :destroy
  belongs_to :survey

  accepts_nested_attributes_for :responses

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :responses, dependent: :destroy
  has_many :answer_choices, dependent: :destroy
  accepts_nested_attributes_for :answer_choices,
      reject_if: proc { |attributes| attributes['content'].blank?}, allow_destroy: true


  def move_down
    next_question = Question.where(number: (self.number + 1)).first
    if next_question
      num = self.number
      self.update(number: next_question.number)
      next_question.update(number: num)
    end
  end

  def move_up
    last_question = Question.where(number: (self.number - 1)).first
    if last_question
      num = self.number
      self.update(number: last_question.number)
      last_question.update(number: num)
    end
  end

end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
  belongs_to :form

  validates :answer, presence: true, if: Proc.new { |a| a.question.required }

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :author
  has_many :questions, dependent: :destroy
  has_many :forms, dependent: :destroy
  has_many :answer_choices, through: :question

  validates :name, uniqueness: true

  accepts_nested_attributes_for :questions, reject_if: proc { |attributes| attributes['text'].blank?},
      allow_destroy: true

  def number_of_results(id)
    a = Form.where(survey_id: id).all
    a.length
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :logged_in?, except: [:new, :create]
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private def logged_in?
    unless Author.find_by_id(session[:user_id])
      redirect_to sessions_login_path, notice: 'User or Password does not match our records.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:email, :password, :first_name, :last_name, :password_confirmation)
    end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  def new
    questions = Question.where(survey_id: params[:survey_id]).all
    @form = Form.new(survey_id: params[:survey_id])
    questions.each do |q|
      @form.responses.build(question: q)
    end
  end

  def create
    @form = Form.new(form_params)
    if @form.save
      flash.now[:notice] = "Thank you for submitting your responses."
    else
      render :new
    end
  end

  private def form_params
    params.require(:form).permit(:survey_id, responses_attributes: [:id, :answer, :question_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    if request.post?
      user = Author.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: "Login Successful"
      else
        flash.now[:notice] = "User and Password do not match our records."
      end
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to sessions_login_path, notice: "Logout Successful"
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :logged_in?
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.where(author_id: session[:user_id])
    @author = session[:user_id]
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @responses = Response.all
  end

  # GET /surveys/new
  def new
    @survey = Survey.new(author_id: session[:user_id])
    @questions = @survey.questions.build
    @answer_choices = 4.times { @questions.answer_choices.build }
  end

  # GET /surveys/1/edit
  def edit
    @questions = @survey.questions.build
    @answer_choices = 4.times { @questions.answer_choices.build }
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to root_path, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to root_path, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private def logged_in?
    unless Author.find_by_id(session[:user_id])
      redirect_to sessions_login_path, notice: 'User or Password does not match our records.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :description, :author_id,
          questions_attributes: [:id, :text, :required, :response_type,
          :_destroy, :number, answer_choices_attributes: [:id, :content, :_destroy]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :new_password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class='editing'>
<h1>Editing<img src='http://www.clker.com/cliparts/1/4/3/4/1258661944702491623drunken_duck_crow_silhouette.svg.hi.png' class='crowpic2'> Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %>
<%= link_to 'Back', authors_path %>
<%= link_to 'Home', root_path %>
</div>

app/views/authors/index.html.erb
<div class='showauthor'>
<h1>Listing <img src='http://www.clker.com/cliparts/1/4/3/4/1258661944702491623drunken_duck_crow_silhouette.svg.hi.png' class='crowpic'> Authors</h1>

<div class='table'>
  <table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.email %></td>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Author', new_author_path %>
<%= link_to 'Home', root_path %>
</div>

app/views/authors/new.html.erb
<header class='header'> Survey<img src='http://www.clker.com/cliparts/1/4/3/4/1258661944702491623drunken_duck_crow_silhouette.svg.hi.png' class='crowpic'> Crow</header>
<div class="signup">
<h1 class="sign-up">Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>
<%= link_to 'Home', root_path %>
</div>

app/views/authors/show.html.erb
<div><img src='http://www.clker.com/cliparts/1/4/3/4/1258661944702491623drunken_duck_crow_silhouette.svg.hi.png' class='crowpic2'>
</div>
<div class='showauthor'>
  <p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %>
<%= link_to 'Back', authors_path %>
<%= link_to 'Home', root_path %>
</div>

app/views/forms/new.html.erb
<div class="form-container">
 <div class="answer-wrapper">
  <%= form_for(@form) do |f| %>
    <% if @form.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@form.errors.count, "error") %> prohibited this question from being saved:</h2>
        <ul>
        <% @form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.hidden_field :survey_id, value: params[:survey_id] %>
    </div>
    <h2><%= @form.survey.name %></h2>
    <%= f.fields_for(:responses) do |ff| %>
      <% question = ff.object.question %>
      <% if question.required %>
        <h6> Required </h6>
      <% end %>
      <%= question.number %>.
      <%= question.text %>
      <div class="field">
        <%= ff.hidden_field :question_id %>
      </div>
      <div class="field">
          <%= ff.label :answer, "Your response" %><br>
          <% if question.response_type == "string" %>
            <%= ff.text_field :answer %>
          <% elsif question.response_type == "text" %>
            <%= ff.text_area :answer %>
          <% elsif question.response_type == "multi" %>
            <%= ff.select :answer, question.answer_choices.map{ |a| [a.content, a.content] }, include_blank: true %>
          <% else %>
            <%= ff.radio_button :answer, 'Yes' %>
            <%= ff.label :answer, "Yes", :value => "yes" %>
            <%= ff.radio_button :answer, "No" %>
            <%= ff.label :answer, "No", :value => "no" %>
          <% end %>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit 'Submit Responses'%>
    </div>

    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyCrow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
</head>
<body>

<%= link_to "Logout", sessions_logout_path if session[:user_id] %>
<p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/surveys/_answer_choices.html.erb
<div class="field">
  <%= f.label :content %><br>
  <%= f.text_field :content %>
</div>
<div class="field">
  <%= f.label :_destroy %>
  <%= f.check_box :_destroy %>
</div>

app/views/surveys/_form.html.erb
<div class="survey-form">
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :author_id %>
  </div>
  
  <div class="question-field">
  </div>
  
 <script id="newQuestion" type="text/html">
  <div class="question-wrapper">
  <h2>Questions</h2>
  <%= f.fields_for :questions do |ff| %>
   
    <%= render 'questions', :f => ff %>
  </div>
  <% end %>
  
</script>
 
  <div class="actions">
    <%= f.submit 'Submit Survey' %>
  </div>
  <button class="add-question">Add Question</button>
 </div> 

<% end %>

app/views/surveys/_questions.html.erb
<div>
  <span><%= f.index + 1 %>. </span>
  <div class="field">
    <%= f.hidden_field :number, value: f.index + 1 %>
  </div>
  <div class="field">
    <%= f.label :text, "Question" %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :response_type %><br>
    <%= f.select :response_type, [["Yes/No", "yes/no"], ["Short Answer", "string"], ["Long Answer", "text"], ["Multiple Choice", "multi"]] %>
  </div>
  <div class="field">
    <%= f.label :required %>
    <%= f.check_box :required %>
  </div>
 <div class="answer-choices">
  <p>Answer Choices</p>
  <div class="answer-choices-field">
 </div>
  
  <%= f.fields_for :answer_choices do |ff| %>
  <%= render 'answer_choices', :f => ff %>
  <% end %>


</div>
  <div class="field">
    <%= f.label :_destroy %>
    <%= f.check_box :_destroy %>
  </div>
</div>

app/views/surveys/edit.html.erb
<img src='http://www.clker.com/cliparts/1/4/3/4/1258661944702491623drunken_duck_crow_silhouette.svg.hi.png' class='crowpic2'>
<div class="form-container">
	<div class="create-container">
		<h1>Editing Survey</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @survey %>
		<%= link_to 'Back', surveys_path %>
		<%= link_to 'Home', root_path %>
	</div>
</div>

app/views/surveys/index.html.erb
<header class='header'> Survey<img src='http://www.clker.com/cliparts/1/4/3/4/1258661944702491623drunken_duck_crow_silhouette.svg.hi.png' class="crowpic"> Crow</header>
<div class="form-container">
<h1>Your Surveys</h1>
<table>
  <thead>
    <tr>
      <th>Survey</th>
      <th>Number of Results</th>
      <th>User Link</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to "#{survey.name}", edit_survey_path(survey.id) %></td>
        <td><%= link_to "#{survey.number_of_results(survey.id)}", survey %></td>
        <td><a href="<%= "http://survey-crow.herokuapp.com/forms/new?survey_id=#{survey.id}" %>"><%= "http://survey-crow.herokuapp.com/forms/new?id=#{survey.id}" %></a></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Make New Survey', new_survey_path %>
<%= link_to 'Edit Your Information', edit_author_path(@author) %>
</div>

app/views/surveys/new.html.erb
<img src='http://www.clker.com/cliparts/1/4/3/4/1258661944702491623drunken_duck_crow_silhouette.svg.hi.png' class='crowpic2'>
<div class="form-container">
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>
<%= link_to 'Home', root_path %>
</div>

app/views/surveys/show.html.erb
<img src='http://www.clker.com/cliparts/1/4/3/4/1258661944702491623drunken_duck_crow_silhouette.svg.hi.png' class='crowpic2'>
<div class="form-container">
<p>
  <strong>Name:</strong>
  <%= @survey.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @survey.description %>
</p>

<p>
  <strong>Questions:</strong>
</p>

<div class="ol">
<ol>
  <% @survey.questions.each do |q| %>
    <% @some_responses = @responses.select{ |response| response.question_id == q.id }%>
      <li><%= q.text %></li>
        <ul>
        <% if q.response_type == 'yes/no' %>
          <% yes = @some_responses.count { |s| s.answer == "Yes" } %>
          <% no = @some_responses.count { |s| s.answer == "No" } %>
          <li>Yes <%= (yes.to_f / @some_responses.count.to_f) * 100 %>%</li>
          <li>No <%= (no.to_f / @some_responses.count.to_f) * 100 %>%</li>
        <% elsif q.response_type == 'multi' %>
          <% @answers = AnswerChoice.where(question_id: q.id).all %>
          <li><ul>
            <% @answers.each do |n| %>
              <% num = @some_responses.count { |s| s.answer == n.content }  %>
              <li><%= n.content %> <%= (num.to_f / @some_responses.count.to_f) * 100 %>%</li>
            <% end %>
          </ul></li>
        <% else %>
          <% @some_responses.each do |r| %>
            <li><%= r.answer %></li>
          <% end %>
        <% end %>
      </ul>
  <% end %>
</ol>
</div>

<%= link_to 'Edit', edit_survey_path(@survey) %>
<%= link_to 'Back', surveys_path %>
<%= link_to 'Home', root_path %>
</div>